
server:
    port: 9999


spring:
    profiles: 
        active: dev
    main: 
        banner-mode: off
    jackson:
        time-zone: Asia/Singapore
        locale: en-PH

---
spring: 
    config: 
        activate:
            on-profile: local-machine
    datasource:
        url: jdbc:mysql://localhost:3306/spring_test?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: 
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
            globally_quoted_identifiers: true
        show-sql: false
        properties:
            hibernate:
                format_sql: false
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
    h2:
        console:
            enabled: true
            path: /h2-console

---

spring: 
    config: 
        activate: 
            on-profile: dev
    security:
        basic: 
            enabled: true
            authorize-mode: NONE
    jpa:
        hibernate:
            ddl-auto: create-drop
            globally_quoted_identifiers: true
        show-sql: false
        database-platform: org.hibernate.dialect.H2Dialect  
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:resting
        username: sa
        password:
        driverClassName: org.h2.Driver
